spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/library
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234567
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
